version: 2
updates:
  # Backend npm
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Backoffice npm
  - package-ecosystem: "npm"
    directory: "/frontend/backoffice"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Dockerfile backend
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Dockerfile backoffice
  - package-ecosystem: "docker"
    directory: "/frontend/backoffice"
    schedule:
      interval: "weekly"
