name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            cd /var/www/applicesi
            docker compose pull
            docker compose up -d --force-recreate --remove-orphans
